### PR TITLE
Fast mode

### PR DESCRIPTION
**Pull request by Simsso**
Introduces a new "watch/CCTV" button which toggles between watching the AI move / battles take place ("slow mode") and a pro "fast mode".
image

In fast mode there are no battle animations, no move animations and the AI moves almost instantly.

### CODE REVIEW

**Comment by Simsso** [comment]
Comment from master @lulebe:
> there are two components to it, a) just remove the timers from the the gamedata/ai.js and b) remove the fight screens and movement animations. For fights that's in controller.js the onFight function and for movement...hmm. Many options where that could be done. Basically just need to keep the moving unit's "movementAnim" (or so) set to null.

**Comment by lulebe** [comment]
Looking great. I'll run a quick test, love it that you easily figured out that iconify stuff and the animation logic. Great to have such competent devs on this project :)

**Comment by Simsso** [comment]
I see only one problem left with the PR: In `compat.js:412` there is a move call and I don't have access to the controller state, so I cannot pass `isFastMode`. Got to figure that out.

**Review by lulebe — APPROVED** [review]
Just tested it and seems to work well. Can be confusing to figure out what actually happened but I'd say that's not the goal of this mode.

**Pull request merged**
